packages:
  - "api"
  - "apps/**"
  - "auth"
  - "packages/**"
  - "scripts"
  - "web"

catalog:
  "@arcstudio/config": "^1"
  "@arcstudio/i18n": "^1"
  typescript: "^5"
  tsx: "^4"
  electron: "^40"

injectWorkspacePackages: true
